id: I696B5033
legacy_id: P004283
ocr_import_info:
  bdrc_scan_id: W23819
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T18:12:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T04:46:18.138189+00:00'
last_modified: 2022-09-02 12:47:06.950941
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23819
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23819
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཀའ་བརྒྱད་གསང་བ་ཡོངས་རྫོགས།
  author: གུ་རུ་ཆོས་དབང་།
statistics:
  ocr_word_mean_confidence_index: 0.6466425389765965
  ocr_word_median_confidence_index: 0.6899999976158142
quality: null
bases:
  I2833:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2833
      total_pages: 512
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2833.txt
    statistics:
      ocr_word_median_confidence_index: 0.6299999952316284
      ocr_word_mean_confidence_index: 0.5906271171880516
    legacy_id: v001
  I2834:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2834
      total_pages: 508
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2834.txt
    statistics:
      ocr_word_median_confidence_index: 0.6100000143051147
      ocr_word_mean_confidence_index: 0.5867301813583569
    legacy_id: v002
  I2835:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2835
      total_pages: 512
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2835.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.6910311054210195
    legacy_id: v003
  I2836:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2836
      total_pages: 480
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I2836.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6755123074954523
    legacy_id: v004
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
