id: I696B5033
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T18:15:17+00:00'
last_modified: '2022-06-07T21:40:24.684616+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23819
  title: བཀའ་བརྒྱད་གསང་བ་ཡོངས་རྫོགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BAAB:
      image_group_id: I2833
      title: ''
      total_pages: 512
      order: 1
      base_file: BAAB.txt
    E63A:
      image_group_id: I2834
      title: ''
      total_pages: 508
      order: 2
      base_file: E63A.txt
    3DA2:
      image_group_id: I2835
      title: ''
      total_pages: 512
      order: 3
      base_file: 3DA2.txt
    D814:
      image_group_id: I2836
      title: ''
      total_pages: 480
      order: 4
      base_file: D814.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
